sudo: false
dist: trusty
language: android
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools
    - android-28

    # The BuildTools version used by your project
    - build-tools-28.0.0

before_script:
  - touch local.properties

before_install:
  - yes | sdkmanager "platforms;android-28"

licenses:
  - '.+'