language: android
dist: trusty
android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository

jdk:
  - oraclejdk8

notifications:
  email: false

cache:
  directories:
    - $HOME/.gradle

before_install:
  - chmod +x ./gradlew
script:
  - ./gradlew