language: android
dist: trusty
android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository
licenses:
  - '*.+'
jdk:
  - oraclejdk8

notifications:
  email: false

cache:
  directories:
    - $HOME/.gradle

before_install:
  - chmod +x ./gradlew
before_script:
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" > "$ANDROID_HOME/licenses/android-sdk-license"
script:
  - ./gradlew